# Generated by Django 5.2.3 on 2025-06-13 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('fashion', 'Fashion'), ('electronics', 'Electronics'), ('books', 'Books'), ('home', 'Home & Living'), ('beauty', 'Beauty')], default='fashion', max_length=50),
        ),
    ]
